### ISSUE TITLE
importing nostr-tools results in bundle exporting it as default

### ISSUE THREAD

**Issue by Giszmo** [nbd-wtf/nostr-tools#19]
I know this might be a long shot but as the issue happens with this import and not with others, I'll leave the issue here in case others ran into the same ...

I'm using the svelte bundler and when I import nostr-tools in service-worker.ts, svelte bundles it, including a default export which I think is the full nostr-tools import.

If I import anything else, Dexie for example, no export is generated in my bundle.

```
$ cat src/service-worker.ts 
import { relayPool } from 'nostr-tools'
$ npm run build
...
  Wrote site to "build"
  ✔ done
$ grep '^export' build/service-worker.js 
export default Fl();
```

Is this a bug in nostr-tools or in the svelte bundler or not a bug at all?? I'm confused.

**Comment by fiatjaf** [comment]
Probably a bug in the way nostr-tools exports itself, which it does by not bundling anything at all.

**Comment by fiatjaf** [comment]
It would be great to know if this is fixed.

**Comment by steida** [comment]
@fiatjaf I was recently creating a JS lib (https://github.com/evoluhq/evolu) and investigated best practices for it

- drop CJS, it's time, bundlers can handle ESM only, and it prevents https://nodejs.org/api/packages.html#dual-package-hazard
- import TS files with .js extension `import { query } from "./query.js";`, so Node.js ESM can handle it.
- export source files for code navigation. "I get so annoyed when "go to definition" just takes me to typescript def files rather than actual code."
- don't bundle code at all. TypeScript is enough.

The reason for ESM only is the ability to use Node.js with ESM. While CJS can use ESM, the opposite does not apply.

**Comment by fiatjaf** [comment]
I am sorry, but I think all your recommendations are bad.

- I can't drop CJS because my Node.js needs that otherwise I have to rename files with the annoying `.mjs` extension which no one uses.
- I don't understand that. If you import TS files with the wrong extension everything will break.
- There are no def files here. Everything is in TypeScript directly.
- I was doing this before (not even with TypeScript, with just normal JS and ES modules) but I've received a thousand million complaints, that's why I started bundling.

I am happy to be convinced I am wrong here, because I also hate bundlers myself.

**Comment by steida** [comment]
> I don't understand that. If you import TS files with the wrong extension everything will break.

No, it's OK. It was actually allowed by the TS compiler for this use case. Look:

https://stackoverflow.com/questions/73336396/how-to-reference-local-file-in-esm-module-when-writing-in-ts

> /**
>  * This script goes through all source files and makes sure
>  * imports end with '.js'. If they don't, the ESM version will
>  * not work. ESM imports must have the full file name.
>  */

https://github.com/koskimas/kysely/blob/master/scripts/check-esm-imports.js 

Kysely, and other ESM-only libs do that.

Otherwise, Node.js would have to use CJS forever, and also libraries authors would have to support both CJS and ESM forever.

**Comment by steida** [comment]
> I can't drop CJS because my Node.js needs that otherwise I have to rename files with the annoying .mjs extension which no one uses.

Node.js CJS can import ESM. Dropping is only for the library. As for "annoying .mjs extension", annoying is legacy code and other people's opinions 😅

**Comment by steida** [comment]
> There are no def files here. Everything is in TypeScript directly.

Yep, it already works. Sorry I didn't check it before.

**Comment by steida** [comment]
> I am happy to be convinced I am wrong here, because I also hate bundlers myself.

Bundling belongs to consumer code (an app using nostr-tools). nostr-tools should not bundle anything, TypeScript compiles is good enough.

**Comment by steida** [comment]
@fiatjaf Of course, do what you want. I just shared my recent experience.

**Comment by chmac** [comment]
I'm trying to build with svelte kit, and I get the following error:

```
import { getPublicKey, nip19 } from "nostr-tools";
         ^^^^^^^^^^^^
SyntaxError: Named export 'getPublicKey' not found. The requested module 'nostr-tools' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'nostr-tools';
const { getPublicKey, nip19 } = pkg;
```

I don't understand enough about the csj / esm stuff to have informed opinions. I did find [this linting report](https://publint.dev/nostr-tools@1.4.1) which suggests that something is not quite right with `module`. In my messing around, I found that by updating `node_modules/nostr-tools/package.json` so that it has the following worked:

```
  "type": "module",
  "main": "./lib/nostr.esm.js",
```

So I need to replace `main` with the value from `module` and add a `type`. Personally, I'll just use patch package to do that so I can move on. But I figured I'd share the info here in case it's helpful in figuring out how to fix the issue.

**Comment by ktecho** [comment]
> I'm trying to build with svelte kit, and I get the following error:
> 
> ```
> import { getPublicKey, nip19 } from "nostr-tools";
>          ^^^^^^^^^^^^
> SyntaxError: Named export 'getPublicKey' not found. The requested module 'nostr-tools' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:

I don't know what's wrong there, but I'm also using it in Svelte and I got no problems doing it like you:

```
import {getEventHash, relayInit, signEvent, validateEvent, getPublicKey, Kind} from "nostr-tools";
```

I have it here:

```
  "devDependencies": {
    "@sveltejs/adapter-node": "1.x",
    "@sveltejs/kit": "1.x",
    "nostr-tools": "^1.4.2",
     [...]
  },
```

**Comment by fiatjaf** [comment]
Welcome to JavaScript.

**Comment by chmac** [comment]
@ktecho I'm building for `adapter-static`, maybe that's the difference?

**Comment by ktecho** [comment]
> @ktecho I'm building for `adapter-static`, maybe that's the difference?

I'm not really sure. Maybe. This is my `svelte.config.js`:

```
import adapter from '@sveltejs/adapter-node';
import sveltePreprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter({ out: 'build' })
	},
	preprocess: sveltePreprocess()
};

export default config;
```

**Comment by steida** [comment]
@fiatjaf That's why I recommended ESM only.

**Comment by jacany** [comment]
> > I'm trying to build with svelte kit, and I get the following error:
> > ```
> > import { getPublicKey, nip19 } from "nostr-tools";
> >          ^^^^^^^^^^^^
> > SyntaxError: Named export 'getPublicKey' not found. The requested module 'nostr-tools' is a CommonJS module, which may not support all module.exports as named exports.
> > CommonJS modules can always be imported via the default export, for example using:
> > ```
> 
> I don't know what's wrong there, but I'm also using it in Svelte and I got no problems doing it like you:
> 
> ```
> import {getEventHash, relayInit, signEvent, validateEvent, getPublicKey, Kind} from "nostr-tools";
> ```
> 
> I have it here:
> 
> ```
>   "devDependencies": {
>     "@sveltejs/adapter-node": "1.x",
>     "@sveltejs/kit": "1.x",
>     "nostr-tools": "^1.4.2",
>      [...]
>   },
> ```

Same thing going on, I just decided to import the raw typescript

https://github.com/jacany/nosbin/blob/205fa1fc40fc993aafcc5d8e1c9baa8d03b9fada/src/lib/Nostr.ts#L25

**Comment by ktecho** [comment]
> Same thing going on, I just decided to import the raw typescript
> 
> https://github.com/jacany/nosbin/blob/205fa1fc40fc993aafcc5d8e1c9baa8d03b9fada/src/lib/Nostr.ts#L25

Is there any readon not to use a more recent version? Some people did some recent changes to the way the app is packaged.

Anyways, I've been using nostr-tools since at least a few months ago and I import it this way and it works fine in SvelteKit:

`import { nip19, Kind, relayInit, getPublicKey, getEventHash, signEvent, validateEvent } from "nostr-tools";`

**Comment by chmac** [comment]
I think something changed in the last 1 or 2 builds, there's a new `esm/` folder in the output which seems to work fine for me now. Also, the linting for 1.7.1 says all good https://publint.dev/nostr-tools@1.7.1

**Comment by jacany** [comment]
> I think something changed in the last 1 or 2 builds, there's a new `esm/` folder in the output which seems to work fine for me now. Also, the linting for 1.7.1 says all good https://publint.dev/nostr-tools@1.7.1

Yup. Time to close this.
