### ISSUE TITLE
Bring noble-curves back instead of noble-secp256k1

### ISSUE THREAD

**Issue by paulmillr** [nbd-wtf/nostr-tools#196]
@fiatjaf why was my PR #187 with noble-curves reverted in ef3184a6e090cd20690414fe36936cd84a3f04d0? Which exact issues did you have with it?

"people are not ready for it, causes BigInt issues" - this is not helpful. noble-secp256k1 uses bigints, curves use bigints, everything is using bigints and there are no issues.

Curves have improved security and a recent audit, which is why it's important to upgrade if you care about these things.

**Comment by fiatjaf** [comment]
It causes issues in some browsers (and maybe React-Native), and I can't figure out why.

![image](https://user-images.githubusercontent.com/1653275/233871506-55fc19e7-497b-47df-810f-b66684fa22ca.png)

I am not really sure what the reason is, but it only happens when `@noble/curves` is present. It was happening before because it was being included, I think, by `@scure/base32`, then I fixed that to make all dependencies only include a single version of `@noble/secp256k1`. Then after your patch it started happening again. I've got reports from two people on Telegram.

![image](https://user-images.githubusercontent.com/1653275/233871697-72714da1-2ed2-4243-ae9f-a79e0c7d32b5.png)

**Comment by paulmillr** [comment]
Noble-curves follow the code style of noble-secp256k1, which is: avoiding bigint literals such as `1n`. This is done for React Native.

Instead, it uses `BigInt(1)`, which works fine in React Native. Same as old secp.

"can't convert bigint to number": sounds like they have shitty browser target which transpiles `**` exponentiation operator to `Math.pow()` which will fail for bigints.

**Comment by fiatjaf** [comment]
That makes sense, which makes my comment "people are not ready for it" even more right now. People are not ready as they're using these stupid transpilers with shitty browser targets.

Thank you for helping and insisting on this, I'll think about it, try to reproduce it and try to come up with a solution that works for non-ready people.

**Comment by paulmillr** [comment]
Secp was using `**` operator in the past.

People just need to configure their browser targets properly. That takes 5 seconds. Because even if you keep using old secp, people will run into this issue sooner or later, in some other dependency.

**Comment by paulmillr** [comment]
The point here is that if every ethereum wallet is ready for curves, nostr should be too. These features are not special, nor new.

I strive to provide support for all possible environments, including react native, common.js, etc. If a lot of users will say something isn't working, it'll be fixed. I have already ensured no bigint literals are used, for example.

The upgrade is not really optional: it contains important security change.

**Comment by paulmillr** [comment]
curves just crossed 100,000 downloads per week: https://www.npmjs.com/package/@noble/curves

The people don't seem to have problems with it, otherwise they'd reported.

**Comment by fiatjaf** [comment]
OK, I will bring it back.

**Comment by fiatjaf** [comment]
Thank you for insisting.

**Comment by paulmillr** [comment]
Thanks @fiatjaf appreciate your work on nostr
