### ISSUE TITLE
default eoseSubTimeout results in hard to debug issues

### ISSUE THREAD

**Issue by Giszmo** [nbd-wtf/nostr-tools#222]
I'm using the pool.list to get bulk amounts of events and I suspect that the default 3.4s timeout is closing sockets on relays that support EOSE or not alike.

Could the default maybe get postponed if in the last 100ms an event was received? That would still get users with poor internet connection talking to relays that take 3.4s to get going due to a complex query for example but it would allow shorter timeouts without issues for most users.

Currently, on pool.sub the timeout starts before iterating over the relays and sending the requests. It's all async, so it should not take too long but I'm for example querying 1000 contact lists at a time from 10 relays ... that means the client has to upload some big requests, relays have to compile some big replies ... no wonder it takes more than 3.4s.

**Comment by fiatjaf** [comment]
I've seen and had issues with the relay component of this library multiple times and I realize it is not great. I was planning on rewriting it from scratch, but then I saw https://github.com/nostr-dev-kit/ndk and maybe people should just use that and I'll remove the relay part from this library?

I haven't tried it yet myself though, that's why I haven't moved forward with this idea.

**Comment by Giszmo** [comment]
I was considering using ndk but there's a lot of "soon to be added" features described. nostr-tools is battle tested.

**Comment by fiatjaf** [comment]
I'm working on rewriting the relay and pool modules entirely, which means this will improve but we will lose all the battle-testedness.
