### ISSUE TITLE
websocket connection fails but the event doesn't make it to my client

### ISSUE THREAD

**Issue by jeremyd** [nbd-wtf/nostr-tools#75]
using "nostr-tools": "^1.1.0"

when using the example for catching an error on the websocket, I don't receive the error (and therefor can't log the status or retry).
```
           relay.on('error', () => {
                console.log(`failed to connect to ${relayUrl}`);
            })
```
^^^this code does not run

In the console I see the error being thrown and not caught on this line:
https://github.com/nbd-wtf/nostr-tools/blob/master/relay.ts#L66

**Comment by christroutner** [comment]
I'm also seeing this error when trying to use nostr-tools in my node.js app. I'm getting this error:

```
ReferenceError: WebSocket is not defined
    at /home/trout/work/nostr/nostr-backup/node_modules/nostr-tools/lib/nostr.cjs.js:190:7
    at new Promise (<anonymous>)
    at connectRelay (/home/trout/work/nostr/nostr-backup/node_modules/nostr-tools/lib/nostr.cjs.js:189:12)
    at Object.connect (/home/trout/work/nostr/nostr-backup/node_modules/nostr-tools/lib/nostr.cjs.js:255:11)
    at connectToLocalRelay (/home/trout/work/nostr/nostr-backup/nostr-backup.js:61:20)
    at start (/home/trout/work/nostr/nostr-backup/nostr-backup.js:52:11)
    at Object.<anonymous> (/home/trout/work/nostr/nostr-backup/nostr-backup.js:57:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)

```

It appears `WebSocket` is a global in the browser space, but does not exist in node.js. I tried to follow ideas in [this StackOverflow question](https://stackoverflow.com/questions/43311238/javascript-referenceerror-websocket-is-not-defined), but the issue is with this library and not my application.

I think it would be better if the [`relayInit()`](https://github.com/nbd-wtf/nostr-tools/blob/master/relay.ts#L34) and [`connectRelay()`](https://github.com/nbd-wtf/nostr-tools/blob/master/relay.ts#L64) function accepted an input variable that contained the `WebSockets` constructor. This would allow node.js to inject the 'ws' library into it at run-time. The browser environment could default to the implicit global variable.

**Comment by christroutner** [comment]
#79 is a hacky demonstration fix for this Issue. I was able to fix my problem, but this solution is incomplete because it needs typing and input validation. This works for node.js, but it needs to be able to fall back to the global WebSockets in the browser context.

**Comment by arkin0x** [comment]
> #79 is a hacky demonstration fix for this Issue. I was able to fix my problem, but this solution is incomplete because it needs typing and input validation. This works for node.js, but it needs to be able to fall back to the global WebSockets in the browser context.

Appreciate the PR but this did not work for me :(

**Comment by monlovesmango** [comment]
for relay.on not firing, did you try setting relay.on after relayInit but before relay.connect()? when I do this I do get the listener to trigger. 

for the websocket not defined issue, did you import the 'websocket-polyfill' for node.js like mentioned in the readme?

**Comment by christroutner** [comment]
> import 'websocket-polyfill'

Thank you for mentioning the polyfill from the README. I did not see that on my first read of it.

**Comment by jeremyd** [comment]
> for relay.on not firing, did you try setting relay.on after relayInit but before relay.connect()? when I do this I do get the listener to trigger.
> 
> for the websocket not defined issue, did you import the 'websocket-polyfill' for node.js like mentioned in the readme?

thank you, setting the callbacks up first is a good idea.  closing issue.
